/*
 * This source file was generated by the Gradle 'init' task
 */
package org.matrix;
import app.src.main.java.org.matrix.ConcurrentBag;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ConcurrentBag c = new ConcurrentBag(2);
        System.out.println(new App().getGreeting());
    }
}
