/*
 * This source file was generated by the Gradle 'init' task
 */
package org.matrix;
import app.src.main.java.org.matrix.ConcurrentBag;
import app.src.main.java.org.matrix.SimpleDataStructure;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ConcurrentBag<SimpleDataStructure> c = new ConcurrentBag<SimpleDataStructure>(2);


        
        c.addItem(0, new SimpleDataStructure());
        c.addItem(0, new SimpleDataStructure());
        c.addItem(1, new SimpleDataStructure());
        c.addItem(1, new SimpleDataStructure());


        System.out.println(c);
        System.out.println(new App().getGreeting());
    }
}
